export type ImplLibrary = "react-v18" | "svelte-v5";

export interface AdapterOptions {
  library: ImplLibrary;
  requiredNames: string[];
  plannedNames: string[];
}

interface LibMeta { pkg: string; adapter: string; }

const LIBS: Record<ImplLibrary, LibMeta> = {
  "react-v18": { pkg: "@syntropic137/default-react-v18", adapter: "reactV18ContractAdapter" },
  "svelte-v5": { pkg: "@syntropic137/default-svelte-v5", adapter: "svelteV5ContractAdapter" }
};

export function renderAdapterModule(opts: AdapterOptions): string {
  const chosen = LIBS[opts.library];
  const other = opts.library === "react-v18" ? LIBS["svelte-v5"] : LIBS["react-v18"];
  const plannedLine = opts.plannedNames.length
    ? `// TODO (planned, not yet required): ${opts.plannedNames.join(", ")}\n`
    : "";

  return `// Generated by @syntropic137/dashboard. The single swap point for this app's UI.
// Required components: ${opts.requiredNames.join(", ")}
${plannedLine}import type { RequiredComponentContracts } from "@syntropic137/contracts";
import { ${chosen.adapter} } from "${chosen.pkg}";
// Swap implementations by changing this one import:
// import { ${other.adapter} } from "${other.pkg}";

export const ui = ${chosen.adapter} satisfies Record<
  keyof RequiredComponentContracts,
  unknown
>;
`;
}
